#!/usr/bin/env python3
"""
VectLLM Constants
Centralized constants and magic numbers
"""

# ASCII Characters
ASCII_SPACE = 32
ASCII_NEWLINE = 10
ASCII_TAB = 9
ASCII_CR = 13

# Default Model Configuration
DEFAULT_EMBED_DIM = 768
DEFAULT_NUM_HEADS = 12
DEFAULT_NUM_LAYERS = 6
DEFAULT_MAX_SEQ_LEN = 512

# Vocabulary Defaults
DEFAULT_CHAR_VOCAB_SIZE = 256
DEFAULT_MAX_WORD_VOCAB_SIZE = 100000
DEFAULT_WORD_CREATION_THRESHOLD = 5
DEFAULT_WORD_PRUNING_THRESHOLD = 2
DEFAULT_MAX_WORD_LENGTH = 20

# Venn Semantic System
DEFAULT_VENN_CLUSTERS = 256
DEFAULT_INTERSECTION_THRESHOLD = 0.5
DEFAULT_CLUSTER_UPDATE_LR = 0.1
DEFAULT_EPISODIC_BUFFER_SIZE = 1024

# Training Defaults
DEFAULT_BASE_LR = 0.0001
DEFAULT_EMBEDDING_LR_SCALE = 0.1
DEFAULT_MOMENTUM = 0.9
DEFAULT_EXPLORATION_TEMPERATURE = 1.0

# Update Frequencies
DEFAULT_VENN_UPDATE_FREQUENCY = 100
DEFAULT_STATS_SYNC_FREQUENCY = 10
DEFAULT_VOCAB_PRUNING_FREQUENCY = 10000

# Sleep Timings (microseconds)
DEFAULT_SELF_LOOP_SLEEP_US = 5000
DEFAULT_EXTERNAL_INPUT_SLEEP_US = 100000

# Checkpoint
DEFAULT_AUTO_CHECKPOINT_INTERVAL = 100
CHECKPOINT_VERSION = 3
MAGIC_V3 = "VECTLLM3"
MAGIC_V2 = "VECTLLM2"
MAGIC_V1 = "VECTLLM"

# File Extensions
CHECKPOINT_EXT = ".ckpt"
VOCAB_EXT = ".vocab"
FREQ_EXT = ".freq"
METADATA_EXT = ".json"

# Stats
DEFAULT_STATS_WINDOW_SIZE = 100
DEFAULT_LOSS_HISTORY_SIZE = 1000

# Formatting
NUMBER_THRESHOLDS = {
    'K': 1_000,
    'M': 1_000_000,
    'B': 1_000_000_000,
}
